#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);


my $event = 'nethserver-wapt-update';
event_actions ( $event, 'initialize-default-databases' => '00');

event_actions($event, qw(
             nethserver-wapt-stop-httpd 01
             nethserver-wapt-enablerepo   10
             nethserver-wapt-postgresql-init 91
             nethserver-wapt-restart-wapt-service  92
             nethserver-wapt-configure-waptserver  99
));

event_templates($event, qw(
                /opt/wapt/waptserver/ssl/cert.pem
                /opt/wapt/waptserver/ssl/key.pem
));

event_services($event, qw(
               nginx restart
));


# certificate update event
event_templates('certificate-update', qw(
                /opt/wapt/waptserver/ssl/cert.pem
                /opt/wapt/waptserver/ssl/key.pem
));

event_services('certificate-update', qw(
               nginx reload
));
