#!/bin/bash

if [[ ! -f '/var/lib/pgsql/9.6/data/PG_VERSION' ]]; then
    /usr/pgsql-9.6/bin/postgresql96-setup initdb
    /usr/sbin/e-smith/config setprop postgresql-9.6 status enabled
fi

/usr/bin/systemctl enable postgresql-9.6
/usr/bin/systemctl restart postgresql-9.6
less
