#!/bin/bash

if [[ -f '/var/lib/nethserver/wapt-backup/backup_wapt.sql' ]]; then

    /usr/bin/sudo -u postgres psql -c "drop database wapt"
    /usr/bin/sudo -u postgres psql < /var/lib/nethserver/wapt-backup/backup_wapt.sql

    if [[ -d '/var/www/html/wapt' ]]; then
        /usr/bin/wapt-scanpackages /var/www/html/wapt
    fi
fi
