#!/bin/bash

if [[ -f '/var/lib/nethserver/wapt-backup/backup_wapt.sql' ]]; then

    /usr/bin/sudo -u postgres psql -c "drop database wapt"
    /usr/bin/sudo -u postgres psql < /var/lib/nethserver/wapt-backup/backup_wapt.sql

    /usr/bin/wapt-scanpackages /var/www/wapt/
fi
