#!/usr/bin/bash

waptserver=$(/usr/bin/systemctl is-active waptserver)
if [[ $waptserver == 'active' ]]; then
    /usr/bin/systemctl restart waptserver
fi

wapttasks=$(/usr/bin/systemctl is-active wapttasks)
if [[ $wapttasks == 'active' ]]; then
    /usr/bin/systemctl restart wapttasks
fi
